/** Pre-filled in the Git Diff Viewer: a two-hunk change, a rename and a new binary file. */
export const GIT_DIFF_SAMPLE = [
  "diff --git a/src/greet.ts b/src/greet.ts",
  "index 3b18e51..a1c2d3f 100644",
  "--- a/src/greet.ts",
  "+++ b/src/greet.ts",
  "@@ -1,6 +1,6 @@",
  " export function greet(name: string) {",
  '-  return "Hello " + name;',
  "+  return `Hello ${name}`;",
  " }",
  " ",
  " export function shout(name: string) {",
  "   return greet(name).toUpperCase();",
  "@@ -20,4 +20,7 @@ export function farewell(name: string) {",
  '   return "Bye " + name;',
  " }",
  " ",
  "-export const VERSION = 1;",
  "+export const VERSION = 2;",
  "+",
  "+/** Greets everyone in the list. */",
  "+export const greetAll = (names: string[]) => names.map(greet);",
  "diff --git a/lib/old-utils.ts b/lib/utils.ts",
  "similarity index 92%",
  "rename from lib/old-utils.ts",
  "rename to lib/utils.ts",
  "index 1111111..2222222 100644",
  "--- a/lib/old-utils.ts",
  "+++ b/lib/utils.ts",
  "@@ -1,3 +1,3 @@",
  " export function clamp(n: number, min: number, max: number) {",
  "-  return Math.min(Math.max(n, min), max);",
  "+  return Math.max(min, Math.min(n, max));",
  " }",
  "diff --git a/public/logo.png b/public/logo.png",
  "new file mode 100644",
  "index 0000000..8f3c2a1",
  "Binary files /dev/null and b/public/logo.png differ",
  "",
].join("\n");
